### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by benIT** [php-opencloud/openstack#282]
Hi,
I am encountering the following error when trying to use your lib: 

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Ob in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 18
```
with that snippet:

```
$requestOptions = [
    'verify' => __DIR__.'/../cacert.pem',
];

$openstack = new OpenStack\OpenStack([
    'authUrl' => $env['auth_url'],
    'region' => $env['region_name'],
    'user' => [
        'name' => $env['username'],
        'password' => $env['password'],
        'domain' => ['name' => $env['domain_name']]

    ],
    'scope' => [
        'project' => ['id' => $env['project_id']],

    ],
    'requestOptions' => $requestOptions
]);

$container = $openstack->objectStoreV1()->getContainer('container1');
```

This sounds to be a classical SSL cert issue.

I tried to set the `verify` option with the cert file path in the client:
	
`	'verify' => __DIR__.'/../cacert.pem',`

I also tried to set my `php.ini` file as follow:

```
[curl]
curl.cainfo = "/var/www/html/cacert.pem"

[openssl]
openssl.cafile= "/var/www/html/cacert.pem"
```

I validate the cert file from the command line with `curl` using this snippet which works fine:

```
curl --cacert "/var/www/html/cacert.pem" --request POST --include --header "Content-Type: application/json" --data '
{
  "auth": {
    "identity": {
      "methods": [
        "password"
      ],
      "password": {
        "user": {
          "domain": { "name": "'$OS_USER_DOMAIN_NAME'" },
          "name": "'$OS_USERNAME'",
          "password": "'$OS_PASSWORD'"
        }
      }
    },
    "scope": {
      "project": {
        "name": "'$OS_PROJECT_NAME'",
        "domain": { "name": "'$OS_USER_DOMAIN_NAME'" }
      }
    }
  }
}
' "$OS_AUTH_URL/auth/tokens"; echo

```

Any idea?

I am running  `PHP 7.1.28` and I use `v3.0.6` of your lib (from composer.lock):

Cheers,
ben

**Comment by haphan** [comment]
Hi @benIT,

Your code looks ok to me. Few things I would try personally,

1. `'verify' => __DIR__.'/../cacert.pem'`. Perhaps, for testing, set CA file using an absolute path just to ensure the path is resolved correctly.  You don't have to change`curl.cainfo` and `openssl.cafile`

2. Try plain curl/guzzle function in PHP to see if it works?

3. Any chance identity endpoint and object storage api use different cert?

**Comment by karimbzu** [comment]
How can we provide 'verify=false' option in $requestOptions?

**Comment by tonicabanas** [comment]
> How can we provide 'verify=false' option in $requestOptions?

```php
  $openstack = new OpenStack([
            'requestOptions' => [
                'verify' => false
            ],
   ....
```

Perhaps a little late, but in case it can be of use to anyone...
